### PR TITLE
Upload this message for Mosquito

### PR DESCRIPTION
**Pull request by reyes-simonejake**
I created a message for Mosquito kindly check it

### CODE REVIEW

**Review by mamasalanang-gerald — APPROVED** [review]
Looks good to me!

**Review by victorioso-daniel-2 — APPROVED** [review]
that's nice

**Review by delumen-ivan — APPROVED** [review]
looks good to me ^_^

**Review by mosquito-michaelangelo — APPROVED** [review]
LGTM

**Pull request merged**
